# -*- coding: utf-8 -*-
"""deliverable2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1444t59fihWdwAzyViPxrVYJLp6wXK8tz
"""

import csv
import pandas as pd
from operator import itemgetter
import re

def sort_tweets():
  total_csvs = ['#dogecoin.csv','#duantewright.csv','#europeansuperleague.csv','#marshelicopter.csv', '#myanmar.csv','DOYOUNG.csv', 'GEICO500.csv', '#ArmenianGenocide.csv', '#BETRemembersDMX.csv', '#supermoon.csv']
  list_of_dataframes = []
  test = []
  for filename in total_csvs:
    list_of_dataframes.append(pd.read_csv(filename))
  merged_df = pd.concat(list_of_dataframes)
  merged_df['Like count'] = merged_df['Like count'].astype(int)
  merged_df = merged_df.sort_values(['Hashtag','Like count'], ascending=[True,False])
  filter_char = lambda c: ord(c) < 256
  merged_df['Text'] = merged_df['Text'].apply(lambda s: ''.join(filter(filter_char, s)))
  merged_df.to_csv('merged_df.csv')

  return merged_df

sort_tweets()

def tentweet():
  cols = ['Hashtag','Tweet1','Tweet2','Tweet3','Tweet4','Tweet5','Tweet6','Tweet7','Tweet8','Tweet9','Tweet10','averageLikes']
  tweets = sort_tweets()

  rows = []
  r =[]
  likes = 0
  i = 0
  rowCount = 0

  ten_output_df = pd.DataFrame(columns=['Hashtag','Tweet1','Tweet2','Tweet3','Tweet4','Tweet5','Tweet6','Tweet7','Tweet8','Tweet9','Tweet10','averageLikes'])
  for _, row in tweets.iterrows():
    if (i + 1)  % 10 == 0:
      r.append(row["Text"])
      likes = likes/10.0
      r.append(likes)
      print(r)
      rowCount += 1
      ten_output_df = ten_output_df.append(pd.Series(r, index=ten_output_df.columns[:len(r)]), ignore_index=True)
      r = []
      likes = 0
    elif (i + 1)  % 10 != 0:
      if (i + 1) % 10 == 1:
        r.append(row["Hashtag"])

      r.append(row["Text"])
      likes += row["Like count"] 
    i+=1

  print(i)
  print(rowCount)

  ten_output_df.to_csv("ten_output.csv", index=False)

tentweet()

def twentytweet():
  cols = ['Hashtag','Tweet1','Tweet2','Tweet3','Tweet4','Tweet5','Tweet6','Tweet7','Tweet8','Tweet9','Tweet10','Tweet11','Tweet12','Tweet13','Tweet14','Tweet15','Tweet16','Tweet17','Tweet18','Tweet19','Tweet20', 'averageLikes']
  tweets = sort_tweets()

  rows = []
  r =[]
  likes = 0
  i = 0
  rowCount = 0

  twenty_output_df = pd.DataFrame(columns=['Hashtag','Tweet1','Tweet2','Tweet3','Tweet4','Tweet5','Tweet6','Tweet7','Tweet8','Tweet9','Tweet10','Tweet11','Tweet12','Tweet13','Tweet14','Tweet15','Tweet16','Tweet17','Tweet18','Tweet19','Tweet20', 'averageLikes'])
  for _, row in tweets.iterrows():
    if (i + 1)  % 20 == 0:
      r.append(row["Text"])
      likes = likes/20.0
      r.append(likes)
      print(r)
      rowCount += 1
      twenty_output_df = twenty_output_df.append(pd.Series(r, index=twenty_output_df.columns[:len(r)]), ignore_index=True)
      r = []
      likes = 0
    elif (i + 1)  % 20 != 0:
      if (i + 1) % 20 == 1:
        r.append(row["Hashtag"])

      r.append(row["Text"])
      likes += row["Like count"] 
    i+=1

  print(i)
  print(rowCount)

  twenty_output_df.to_csv("twenty_output.csv", index=False)

twentytweet()

def notweet():
  tweets = sort_tweets()
  cols = ['Hashtag','Average Likes']

  rows = []
  r =[]
  likes = 0
  i = 0
  rowCount = 0

  nolike_output_df = pd.DataFrame(columns=['Hashtag'])
  for _, row in tweets.iterrows():
    if (i + 1)  % 20 == 0:
      print(r)
      rowCount += 1
      nolike_output_df = nolike_output_df.append(pd.Series(r, index=nolike_output_df.columns[:len(r)]), ignore_index=True)
      r = []
      likes = 0
    elif (i + 1)  % 20 != 0:
      if (i + 1) % 20 == 1:
        r.append(row["Hashtag"])

    i+=1

  print(i)
  print(rowCount)

  nolike_output_df.to_csv("zero_output.csv", index=False)

notweet()